#
# plot histograms of reflecting particles
#
from matplotlib import pyplot as plt
import HistUtil
class PlotReflections(object):
    def __init__(self,savefile):
        self.HNST = HistUtil.load_hist(name="NInter",label="All ST",file=savefile)
        self.HNIPA = HistUtil.load_hist(name="NInter",label="All IPA",file=savefile)
        self.HNSTTgt = HistUtil.load_hist(name="NInter",label="Target ST",file=savefile)
        self.HNIPATgt = HistUtil.load_hist(name="NInter",label="Target IPA",file=savefile)
        self.HDnMom = HistUtil.load_hist(name="DnMom",label="All",file=savefile)
        self.HDnTgtMom = HistUtil.load_hist(name="DnMom",label="Target",file=savefile)
        self.HDnNoTgtMom = HistUtil.load_hist(name="DnMom",label="No Target",file=savefile)
        self.HDnNoIPAMom = HistUtil.load_hist(name="DnMom",label="No IPA",file=savefile)
        self.HDnNoMatMom = HistUtil.load_hist(name="DnMom",label="No Mat",file=savefile)
        self.HUpMom = HistUtil.load_hist(name="UpMom",label="All",file=savefile)
        self.HUpTgtMom = HistUtil.load_hist(name="UpMom",label="Target",file=savefile)
        self.HUpNoTgtMom = HistUtil.load_hist(name="UpMom",label="No Target",file=savefile)
        self.HUpNoIPAMom = HistUtil.load_hist(name="UpMom",label="No IPA",file=savefile)
        self.HUpNoMatMom = HistUtil.load_hist(name="UpMom",label="No Mat",file=savefile)
        self.HDeltaMom = HistUtil.load_hist(name="DeltaMom",label="All",file=savefile)
        self.HDeltaTgtMom = HistUtil.load_hist(name="DeltaMom",label="Target",file=savefile)
        self.HDeltaNoTgtMom = HistUtil.load_hist(name="DeltaMom",label="No Target",file=savefile)
        self.HDeltaNoIPAMom = HistUtil.load_hist(name="DeltaMom",label="No IPA",file=savefile)
        self.HDeltaNoMatMom = HistUtil.load_hist(name="DeltaMom",label="No Mat",file=savefile)
        self.HDeltaTgtMomB12 = HistUtil.load_hist(name="DeltaMom",label="B12",file=savefile)
        self.HDeltaTgtMomB34 = HistUtil.load_hist(name="DeltaMom",label="B34",file=savefile)
        self.HDeltaTgtMomB56 = HistUtil.load_hist(name="DeltaMom",label="B56",file=savefile)
        self.HDeltaTgtMomB78 = HistUtil.load_hist(name="DeltaMom",label="B78",file=savefile)
        self.HDeltaTgtMomB9p = HistUtil.load_hist(name="DeltaMom",label="B9p",file=savefile)

    def PlotIntersections(self):
        fig, (cmat,cselmat) = plt.subplots(1,2,layout='constrained', figsize=(15,5))
        nipa = HistUtil.plot(self.HNIPA,cmat)
        nst = HistUtil.plot(self.HNST,cmat)
        cmat.legend(loc="upper right")
        nipasel = HistUtil.plot(self.HNIPATgt,cselmat)
        nstsel = HistUtil.plot(self.HNSTTgt,cselmat)
        cselmat.legend(loc="upper right")

    def PlotMomentum(self):
        fig, (upMom, dnMom, deltaMom) = plt.subplots(1,3,layout='constrained', figsize=(15,5))
        upmom = HistUtil.plot(self.HUpMom,upMom)
        uptgtmom = HistUtil.plot(self.HUpTgtMom,upMom)
        upnotgtmom = HistUtil.plot(self.HUpNoTgtMom,upMom)
        upnoipamom = HistUtil.plot(self.HUpNoIPAMom,upMom)
        upnomatmom = HistUtil.plot(self.HUpNoMatMom,upMom)
        upMom.legend(loc="upper right")
        dnmom = HistUtil.plot(self.HDnMom,dnMom)
        dntgtmom = HistUtil.plot(self.HDnTgtMom,dnMom)
        dnnotgtmom = HistUtil.plot(self.HDnNoTgtMom,dnMom)
        dnnoipamom = HistUtil.plot(self.HDnNoIPAMom,dnMom)
        dnnomatmom = HistUtil.plot(self.HDnNoMatMom,dnMom)
        dnMom.legend(loc="upper right")
        delmom = HistUtil.plot(self.HDeltaMom,deltaMom)
        deltgtmom = HistUtil.plot(self.HDeltaTgtMom,deltaMom)
        delnotgtmom = HistUtil.plot(self.HDeltaNoTgtMom,deltaMom)
        delnoipamom = HistUtil.plot(self.HDeltaNoIPAMom,deltaMom)
        delnomatmom = HistUtil.plot(self.HDeltaNoMatMom,deltaMom)
        deltaMom.legend(loc="upper right")

    def PlotBinnedMomentum(self):
        fig, (deltaMom) = plt.subplots(1,1,layout='constrained', figsize=(15,5))
        B12 = HistUtil.plot(self.HDeltaTgtMomB12,deltaMom)
        B34 = HistUtil.plot(self.HDeltaTgtMomB34,deltaMom)
        B56 = HistUtil.plot(self.HDeltaTgtMomB56,deltaMom)
        B78 = HistUtil.plot(self.HDeltaTgtMomB78,deltaMom)
        B9p = HistUtil.plot(self.HDeltaTgtMomB9p,deltaMom)
        deltaMom.legend(loc="upper right")
